version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - cd portfolio
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: portfolio/out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*