version: 1.0
frontend:
  phases:
    preBuild:
      commands:
        - cd portfolio_project/portfolio
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: portfolio_project/portfolio/.next
    files:
      - '**/*'
  cache:
    paths:
      - portfolio_project/portfolio/node_modules/**/*